### ISSUE TITLE
class could not extends "BeanBox"

### ISSUE THREAD

**Issue by xiaoCong2014** [drinkjava2/jBeanBox#1]
I create a new class named "MyBox" and try  "public class MyBox extends BeanBox", but :
1, eclipse IDE could not find class  named "BeanBox",
2, "import com.mchange.v2.c3p0.ComboPooledDataSource; "  is error.
my environment :
IDE:  eclipse for J2EE  Neon version .
I have download all the jars from:
http://central.maven.org/maven2/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
http://central.maven.org/maven2/asm/asm/3.3.1/asm-3.3.1.jar
http://central.maven.org/maven2/org/aspectj/aspectjrt/1.8.9/aspectjrt-1.8.9.jar
http://central.maven.org/maven2/cglib/cglib/2.2.2/cglib-2.2.2.jar
and
add they to build path.

**Comment by drinkjava2** [comment]
Hi XiaoCong2014, seems you did not find the BeanBox.java file, this is the only file you need.
but anyway, I've already use Maven to mange the project, please run below in windows command line:
(after installed git https://git-scm.com/downloads and Maven)
git clone https://github.com/drinkjava2/jBeanBox
cd jbeanbox
mvn install
然后你就可以在jBeanBox目录下找到所有的jar包了。
运行mvn eclipse:eclipse后可导入eclipse.
